# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 377b4e51adfe8d24e4bd7f399679581707b5073d8b778826b7a04281c6f31efcfc7a01c60e3cb509f977e0ce2eb018fbab88ddc864326b68dccf3b12bc420d98

test:
  secret_key_base: d91d400c949a519fe444803d9e43f4b14cd6473965b6bcfec4067b1adaa592997399ff808ecf039ba5228ddc7076a6de66ba4a9caaa7d810baf5afcf99d2af57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
